# Digital Signage
# MOD
# VERSION	0.5.0

FROM	base
MAINTAINER	Ben Rhoads "benjamin.p.rhoads@nasa.gov"

#Update repository
RUN echo "Updating apt-get"
RUN apt-get update

RUN echo "Installing smbclient, ping, python, pip"
RUN apt-get install -y smbclient iputils-ping python python-pip